version: '3'
services:
  # develop mode
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"

  # production mode
  node_prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3333:3000"
