version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sample-app:/usr/src/app
    command: sh -c "npm run dev" # develop mode
    #command: sh -c "npm run build && npm run start" # production mode
    ports:
      - "3000:3000"